Bump libx265 to 2.1.

diff --git a/scripts/libx265 b/scripts/libx265
--- a/scripts/libx265
+++ b/scripts/libx265
@@ -5,17 +5,13 @@ __DIR__=$(dirname "${__FILE__}")
 . $__DIR__/common.inc
 
 NAME=libx265
-VERSION=hg-master
+VERSION=2.1
 
 do_download()
 {
   info "Download $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
   cd_src
-  # Delete directory if exists
-  if [ -d "x265" ]; then
-    run rm -rf x265
-  fi
-  if ! hg clone https://bitbucket.org/multicoreware/x265; then
+  if ! wget https://bitbucket.org/multicoreware/x265/downloads/x265_${VERSION}.tar.gz -O x265_${VERSION}.tar.gz; then
     error "Failed to download $NAME"
   fi
   info "Download complete"
@@ -24,14 +20,17 @@ do_download()
 do_unpack()
 {
   info "Unpack $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
-  echo "Nothing to do."
+  cd_src
+  if ! tar xzvf x265_${VERSION}.tar.gz; then
+    error "Failed to unpack $NAME"
+  fi
   info "Unpack complete"
 }
 
 do_configure()
 {
   info "Configure $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
-  cd_src x265/build/linux
+  cd_src x265_${VERSION}/build/linux
   if ! cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="$BUILD_DIR" -DENABLE_SHARED:bool=off ../../source; then
     error "Failed to configure $NAME"
   fi
@@ -41,7 +40,7 @@ do_configure()
 do_compile()
 {
   info "Compile $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
-  cd_src x265/build/linux
+  cd_src x265_${VERSION}/build/linux
   if ! make; then
     error "Failed to compile $NAME"
   fi
@@ -51,7 +50,7 @@ do_compile()
 do_install()
 {
   info "Install $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
-  cd_src x265/build/linux
+  cd_src x265_${VERSION}/build/linux
   if ! make install; then
     error "Failed to install $NAME"
   fi
@@ -61,7 +60,7 @@ do_install()
 do_clean()
 {
   info "Clean $NAME [ ${C_RUN}${VERSION}${C_INFO} ] ..."
-  cd_src x265/build/linux
+  cd_src x265_${VERSION}/build/linux
   if ! make clean; then
     error "Failed to clean $NAME"
   fi
